runtime: nodejs10
env: standard

resources:
  cpu: 1
  memory_gb: 0.256
  disk_size_gb: 0.25

automatic_scaling:
  min_instances: 1
  max_instances: 15
  target_throughput_utilization: 0.7
  target_cpu_utilization: 0.7
